app:
  datasource:
    dbpreme:
      url: jdbc:postgresql://10.0.0.128:5432/DBPREMEH
      username: upremeh
      password: upremeh

    dbedu:
      url: jdbc:postgresql://10.0.0.128:5432/DBEDUH
      username: ueduchm
      password: ueduchm

    dbergon:
      url: jdbc:oracle:thin:@10.0.0.208:1521:ERGONH
      username: edunet
      password: ensalamento

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: com.br.gov.ms.campogrande.apireme.config.LegacyPostgreSQLDialect

  sql:
    init:
      platform: postgres

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: https://autenticacao-h.campogrande.ms.gov.br/auth/realms/campograndems
      resourceserver:
        jwt:
          jwk-set-uri: https://autenticacao-h.campogrande.ms.gov.br/auth/realms/campograndems/protocol/openid-connect/certs